=== doughoff/JV-394/xsd/rss-russian-doll.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="rss">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="channel">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="title"/>
              <xs:element type="xs:anyURI" name="link"/>
              <xs:element type="xs:string" name="description"/>
              <xs:element type="xs:string" name="language"/>
              <xs:element type="xs:string" name="copyright"/>
              <xs:element type="xs:string" name="category"/>
 <xs:element name="item" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
<xs:element type="xs:string" name="title"/>
                    <xs:element type="xs:anyURI" name="link"/>
<xs:element type="xs:string" name="description"/>
                    <xs:element name="enclosure" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="url" use="optional"/>
                            <xs:attribute type="xs:byte" name="length" use="optional"/><xs:attribute type="xs:string" name="type" use="optional"/>
                            <xs:attribute type="xs:string" name="caption" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="pubDate"/>
                    <xs:element name="guid">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:int">
                            <xs:attribute type="xs:string" name="isPermaLink" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:float" name="version"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== doughoff/JV-394/xsd/topstories-rss.xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Student/Desktop/XML/rss-russian-doll.xsd">
    <channel>
        <title>Top Stories</title>
        <link>http://www.kmbc.com</link>
        <description/>
        <language>en-US</language>
        <copyright>Hearst Television, Inc.</copyright>
        <category>Home</category>
                    <item>
                <title>&#039;Excellence First!&#039;: 6th graders&#039; uplifting rap video goes viral</title>
                <link>http://www.kmbc.com/article/excellence-first-6th-graders-uplifting-rap-video-goes-viral/13115276</link>
                <description>&lt;p&gt;A rap video featuring school children, set to the beat of Tee Grizzley&#039;s &quot;First Day Out,&quot; has taken social media by storm and attracted the attention of some high profile people, including former first lady Michelle Obama.&lt;/p&gt;</description>
                                    <enclosure url="https://hips.htvapps.com/htv-prod-media.s3.amazonaws.com/images/excellence-first-video-1509304815.jpg" length="0" type="image/jpeg" caption=""/>
                                <pubDate>Sun, 29 Oct 2017 20:31:38 GMT</pubDate>
                <guid isPermaLink="false">13115276</guid>
            </item>
                    <item>
                <title>Thief steals parts of neighborhood &#039;Nightmare Before Christmas&#039; Halloween display</title>
                <link>http://www.kmbc.com/article/thief-steals-parts-of-neighborhood-nightmare-before-christmas-halloween-display/13067379</link>
                <description>&lt;p&gt;“He hand-makes every decoration, so this is not something he buys. He hand cuts them out of wood, he paints them, and he decorates every neighbor’s yard.&quot;&lt;/p&gt;</description>
                                    <enclosure url="https://hips.htvapps.com/htv-prod-media.s3.amazonaws.com/images/capture-jpg-1508688962.jpg" length="0" type="image/jpeg" caption=""/>
                                <pubDate>Sun, 22 Oct 2017 23:45:34 GMT</pubDate>
                <guid isPermaLink="false">13067379</guid>
            </item>
                    <item>
                <title>Police discover ID theft ring after suspects leave $7 unpaid bill</title>
                <link>http://www.kmbc.com/article/police-discover-id-theft-ring-after-suspects-leave-dollar7-unpaid-bill/13058883</link>
                <description>&lt;p&gt;“Let this be a lesson on etiquette as well; pay your bill and tip your waitress.”&lt;/p&gt;</description>
                                    <enclosure url="https://hips.htvapps.com/htv-prod-media.s3.amazonaws.com/images/pearlriverarrests-1508443726.jpg" length="0" type="image/jpeg" caption=""/>
                                <pubDate>Fri, 20 Oct 2017 15:53:22 GMT</pubDate>
                <guid isPermaLink="false">13058883</guid>
            </item>
                    <item>
                <title>Biracial boy allegedly hanged by group of teens gets big birthday surprise</title>
                <link>http://www.kmbc.com/article/biracial-boy-allegedly-hanged-by-group-of-teens-gets-big-birthday-surprise/12475245</link>
                <description>&lt;p&gt;Last month, Quincy&#039;s family said a group of teenagers nearly hanged him in what they&#039;re calling a racially motivated crime. &lt;/p&gt;</description>
                                    <enclosure url="https://hips.htvapps.com/htv-prod-media.s3.amazonaws.com/images/neck-rope-png-1505300549.png" length="0" type="image/png" caption=""/>
                                <pubDate>Thu, 12 Oct 2017 00:52:59 GMT</pubDate>
                <guid isPermaLink="false">12475245</guid>
            </item>
                    <item>
                <title>Marathoners&#039; goals, personal records impacted after route finishes 4,200 feet short</title>
                <link>http://www.kmbc.com/article/another-marathon-mistake-runners-complain-route-was-too-short/13051156</link>
                <description>&lt;p&gt;The &quot;human error&quot; in Milwaukee comes a year after some runners ran too long.&lt;/p&gt;</description>
                                    <enclosure url="https://hips.htvapps.com/htv-prod-media.s3.amazonaws.com/images/2017-pnc-milwaukee-marathon-101517-1-1508356335.jpg" length="0" type="image/jpeg" caption=""/>
                                <pubDate>Thu, 19 Oct 2017 14:22:09 GMT</pubDate>
                <guid isPermaLink="false">13051156</guid>
            </item>
                    <item>
                <title>Police: Man found sleeping in stranger&#039;s home with cocaine</title>
                <link>http://www.kmbc.com/article/police-vt-man-found-sleeping-in-strangers-home-with-cocaine/13116841</link>
                <description>&lt;p&gt;A Vermont man is facing charges after allegedly sleeping in someone else&#039;s home, state police said.&lt;/p&gt;</description>
                                    <enclosure url="https://hips.htvapps.com/htv-prod-media.s3.amazonaws.com/images/barber-cocaine-1509355556.jpg" length="0" type="image/jpeg" caption=""/>
                                <pubDate>Mon, 30 Oct 2017 09:27:35 GMT</pubDate>
                <guid isPermaLink="false">13116841</guid>
            </item>
                    <item>
                <title>This App Is Going Away Soon</title>
                <link>http://www.kmbc.com/article/this-app-is-going-away-soon/13099412</link>
                <description>&lt;p&gt;Download our main app for custom alerts and interactive radar&lt;/p&gt;</description>
                                    <enclosure url="https://hips.htvapps.com/htv-prod-media.s3.amazonaws.com/images/kmbc-1509040465.png" length="0" type="image/png" caption=""/>
                                <pubDate>Mon, 01 Jan 2018 04:55:00 GMT</pubDate>
                <guid isPermaLink="false">13099412</guid>
            </item>
                    <item>
                <title>Meth found among Halloween trick-or-treat candy</title>
                <link>http://www.kmbc.com/article/meth-found-among-trick-or-treat-halloween-candy/13121633</link>
                <description>&lt;p&gt;Police are warning families that candy that was received during a community trick-or-treating event should be thrown away.&lt;/p&gt;</description>
                                    <enclosure url="https://hips.htvapps.com/htv-prod-media.s3.amazonaws.com/images/halloween-candy-flickr-1509392906.jpg" length="0" type="image/jpeg" caption=""/>
                                <pubDate>Mon, 30 Oct 2017 19:58:00 GMT</pubDate>
                <guid isPermaLink="false">13121633</guid>
            </item>
                    <item>
                <title>Viral photos of college student spurs modeling agency calls</title>
                <link>http://www.kmbc.com/article/viral-photos-of-college-student-spurs-modeling-agency-calls/13117075</link>
                <description>&lt;p&gt;Two photographs of a Plymouth State University student that have gone viral on social media are bringing her dreams of becoming a model closer to reality.&lt;/p&gt;</description>
                                    <enclosure url="https://hips.htvapps.com/htv-prod-media.s3.amazonaws.com/images/img-thesunk-anok-yai-1509335155.png" length="0" type="image/png" caption=""/>
                                    <enclosure url="https://hips.htvapps.com/htv-prod-media.s3.amazonaws.com/images/img-thesunk-anok-yai-1509335155.png" length="0" type="image/png" caption=""/>
                                    <enclosure url="https://hips.htvapps.com/htv-prod-media.s3.amazonaws.com/images/img-thesunk-anok-yai-2-1509335084.png" length="0" type="image/png" caption=""/>
                                <pubDate>Mon, 30 Oct 2017 19:52:00 GMT</pubDate>
                <guid isPermaLink="false">13117075</guid>
            </item>
                    <item>
                <title>‘House of Cards’ will end after sixth season, confirms Netflix </title>
                <link>http://www.kmbc.com/article/house-of-cards-will-end-after-sixth-season-confirms-netflix/13121664</link>
                <description>&lt;p&gt;Production for the sixth season has reportedly begun and is scheduled to premiere sometime in 2018. &lt;/p&gt;</description>
                                    <enclosure url="https://hips.htvapps.com/htv-prod/ibmig/cms/image/national-desk/24639332-24639332.jpg" length="0" type="image/jpeg" caption=""/>
                                <pubDate>Mon, 30 Oct 2017 19:50:00 GMT</pubDate>
                <guid isPermaLink="false">13121664</guid>
            </item>
                    <item>
                <title>Tony Podesta steps down from lobbying firm</title>
                <link>http://www.kmbc.com/article/tony-podesta-steps-down-from-lobbying-firm/13121577</link>
                <description>&lt;p&gt;Tony Podesta, a major Democratic Washington player, is stepping aside from his lobbying firm amid the special counsel&#039;s investigation&lt;/p&gt;</description>
                                    <enclosure url="https://hips.htvapps.com/htv-prod-media.s3.amazonaws.com/images/tony-podesta-1509392347.jpg" length="0" type="image/jpeg" caption=""/>
                                <pubDate>Mon, 30 Oct 2017 19:49:00 GMT</pubDate>
                <guid isPermaLink="false">13121577</guid>
            </item>
                    <item>
                <title>Manafort, Gates plead not guilty to conspiracy, 11 other charges</title>
                <link>http://www.kmbc.com/article/report-paul-manafort-told-to-surrender-to-federal-authorities/13117535</link>
                <description>&lt;p&gt;Paul Manafort, President Donald Trump&#039;s ex-campaign chairman, has pleaded not guilty to conspiracy, and 11 other charges filed against him in federal court&lt;/p&gt;</description>
